title: 'Code for Life'
tagline: 'Code for Life Documentation'
description: 'Inspire the next generation of computer scientists'
github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
